const darkTheme = {
  '.tmtodos-dark': {
    '--tmtodos-colors-brand': 'hsla(var(--palette-blue-35), 100%)',
    '--tmtodos-colors-body': 'hsla(var(--palette-gray-90), 100%)',
    '--tmtodos-colors-header': 'hsla(var(--palette-gray-90), 40%)',
    '--tmtodos-colors-emphasis': 'hsla(var(--palette-blue-35), 10%)',
    '--tmtodos-colors-foreground': 'hsla(var(--palette-gray-80), 60%)',
    '--tmtodos-colors-danger': 'hsla(var(--palette-red-30), 100%)',
    '--tmtodos-colors-danger-emphasis': 'hsla(var(--palette-red-40), 15%)',
    '--tmtodos-colors-warning': 'hsla(var(--palette-orange-45), 100%)',
    '--tmtodos-colors-warning-emphasis': 'hsla(var(--palette-orange-45), 15%)',
    '--tmtodos-colors-success': 'hsla(var(--palette-green-45), 100%)',
    '--tmtodos-colors-success-emphasis': 'hsla(var(--palette-green-45), 15%)',
    '--tmtodos-colors-typeface-primary': 'hsla(var(--palette-indigo-05), 100%)',
    '--tmtodos-colors-typeface-secondary': 'hsla(var(--palette-gray-35), 100%)',
    '--tmtodos-colors-typeface-tertiary': 'hsla(var(--palette-gray-20), 100%)',
    '--tmtodos-colors-typeface-danger': 'hsla(var(--palette-red-20), 100%)',
    '--tmtodos-border-color': 'hsl(var(--palette-gray-80))',
    '--tmtodos-card-background-color': 'hsl(var(--palette-gray-88))',
    '--tmtodos-form-input-active': 'var(--tmtodos-colors-brand)',
    '--tmtodos-form-input-background': 'hsl(var(--palette-gray-100))',
    '--tmtodos-form-input-disabled': 'hsl(var(--palette-gray-55))',
    '--tmtodos-form-input-border': 'hsl(var(--palette-gray-60))',
    '--tmtodos-form-input-focus': 'hsla(var(--palette-blue-50), 1)',
    '--shadow-color': 'var(--local-shadow-color, 223deg 5% 1%)',
    '--code-snippet-background': 'hsla(var(--palette-gray-85), 0.5)',
    '--token-comment': 'var(--tmtodos-colors-typeface-tertiary)',
    '--token-selector': 'hsl(var(--palette-indigo-20))',
    '--token-symbol': 'hsl(var(--palette-blue-35))',
    '--token-operator': 'hsl(var(--palette-orange-35))',
    '--token-keyword': 'hsl(var(--palette-blue-30))',
    '--token-function': 'hsl(var(--palette-pink-35))',
    '--token-punctuation': 'hsl(var(--palette-indigo-20))',
  },
};

export default darkTheme;
