export const CREATE_NOTE_REQUEST = 'CREATE_NOTE_REQUEST';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_FAIL = 'CREATE_NOTE_FAIL';

export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL';

export const LIST_NOTES_REQUEST = 'LIST_NOTES_REQUEST';
export const LIST_NOTES_SUCCESS = 'LIST_NOTES_SUCCESS';
export const LIST_NOTES_FAIL = 'LIST_NOTES_FAIL';
