import axios from 'axios';
import {
  CREATE_NOTE_FAIL,
  CREATE_NOTE_REQUEST,
  CREATE_NOTE_SUCCESS,
  UPDATE_NOTE_FAIL,
  UPDATE_NOTE_REQUEST,
  UPDATE_NOTE_SUCCESS,
  DELETE_NOTE_FAIL,
  DELETE_NOTE_REQUEST,
  DELETE_NOTE_SUCCESS,
  LIST_NOTES_FAIL,
  LIST_NOTES_REQUEST,
  LIST_NOTES_SUCCESS,
} from '../constants/noteConstants';